apiVersion: v1
kind: Secret
metadata:
  name: materios-blob-gateway-secret
  namespace: materios
type: Opaque
data:
  BLOB_GATEWAY_API_KEY: ZWUyNjVjODRiODQwNDdlZWU1ZWU4OWEwNDkzNDY3YWM5YmI4MjJhN2JiY2NhZWQwOGRmMjA1NWZkY2JlYjU0Mw==
